# Generated by Django 4.2 on 2023-05-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocksite', '0002_localizacao_remove_pontodeamostragem_localizacao_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horizonte',
            old_name='kci',
            new_name='kcl',
        ),
        migrations.AlterField(
            model_name='horizonte',
            name='profundidade_inferior',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='horizonte',
            name='profundidade_superior',
            field=models.IntegerField(null=True),
        ),
    ]
