# Generated by Django 4.2 on 2023-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocksite', '0003_rename_kci_horizonte_kcl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontodeamostragem',
            name='uso_atual',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
